title: "Anish Nilesh Rane - ML/AI Engineer"
description: "Machine Learning and AI Portfolio"
baseurl: "/Portfolio"
url: "https://anishrane-cox.github.io"

author:
  name: Anish Nilesh Rane
  email: anishrane2000@gmail.com

markdown: kramdown
plugins:
  - jekyll-feed
