title: "Anish Nilesh Rane - ML/AI Engineer"
description: "Transforming data into intelligent solutions. Passionate about deep learning, computer vision, and building AI systems that make a difference."

# Site settings - FIXED URL configuration
baseurl: "/Portfolio"
url: "https://anishrane-cox.github.io"

# Personal Info
author:
  name: Anish Nilesh Rane
  email: anishrane2000@gmail.com
  linkedin: https://www.linkedin.com/in/anish-rane
  github: https://github.com/AnishRane-cox
  phone: "(+91) 7058305706"

# SEO & Social Metadata
lang: "en"
logo: "/assets/images/profile.jpg"
social:
  name: "Anish Nilesh Rane"
  links:
    - "https://www.linkedin.com/in/anish-rane"
    - "https://github.com/AnishRane-cox"

# Twitter metadata
twitter:
  username: "anish_rane"
  card: "summary_large_image"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Plugins (removed jekyll-paginate as it may cause issues)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults (fixed duplicate defaults)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: "/assets/images/og-image.jpg"
      twitter_card: "summary_large_image"
      lang: "en"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      image: "/assets/images/og-image.jpg"
      twitter_card: "summary_large_image"
      lang: "en"

# Pagination
paginate: 6
paginate_path: "/blog/page:num/"

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - node_modules
  - vendor
